# @author zhangzhihao
"""小说规划常量。"""

MIN_OUTLINE_CHAPTERS = 8
ABSOLUTE_MAX_CHAPTERS = 10000
USER_TARGET_FLEX = 200
DEFAULT_SUGGESTED_CHAPTERS = 80

L1_BATCH_SIZE = 25
L2_BATCH_SIZE = 10
L2_INITIAL_WINDOW = 60
L2_EXPAND_AHEAD = 30
